/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>, never>
    '/asset/enclosure/enclosure/': RouteRecordInfo<
      '/asset/enclosure/enclosure/',
      '/asset/enclosure/enclosure',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/asset/enclosure/enclosure/add-enclosure': RouteRecordInfo<
      '/asset/enclosure/enclosure/add-enclosure',
      '/asset/enclosure/enclosure/add-enclosure',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/asset/enclosure/enclosure/detail-enclosure': RouteRecordInfo<
      '/asset/enclosure/enclosure/detail-enclosure',
      '/asset/enclosure/enclosure/detail-enclosure',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/asset/enclosure/enclosure/edit-enclosure': RouteRecordInfo<
      '/asset/enclosure/enclosure/edit-enclosure',
      '/asset/enclosure/enclosure/edit-enclosure',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/asset/enclosure/enclosure-floor': RouteRecordInfo<
      '/asset/enclosure/enclosure-floor',
      '/asset/enclosure/enclosure-floor',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/asset/enclosure/floor/': RouteRecordInfo<
      '/asset/enclosure/floor/',
      '/asset/enclosure/floor',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/asset/enclosure/floor/add-floor': RouteRecordInfo<
      '/asset/enclosure/floor/add-floor',
      '/asset/enclosure/floor/add-floor',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/asset/enclosure/floor/detail-floor': RouteRecordInfo<
      '/asset/enclosure/floor/detail-floor',
      '/asset/enclosure/floor/detail-floor',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/asset/enclosure/floor/edit-floor': RouteRecordInfo<
      '/asset/enclosure/floor/edit-floor',
      '/asset/enclosure/floor/edit-floor',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/dashboard': RouteRecordInfo<
      '/dashboard',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/home-view': RouteRecordInfo<
      '/home-view',
      '/home-view',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>, never>
    '/management/personnel/add-personnel': RouteRecordInfo<
      '/management/personnel/add-personnel',
      '/management/personnel/add-personnel',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/management/personnel/detail-personnel': RouteRecordInfo<
      '/management/personnel/detail-personnel',
      '/management/personnel/detail-personnel',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/management/personnel/import-personnel': RouteRecordInfo<
      '/management/personnel/import-personnel',
      '/management/personnel/import-personnel',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/management/personnel/import-personnel-complete': RouteRecordInfo<
      '/management/personnel/import-personnel-complete',
      '/management/personnel/import-personnel-complete',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/management/personnel/import-personnel-execute': RouteRecordInfo<
      '/management/personnel/import-personnel-execute',
      '/management/personnel/import-personnel-execute',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/management/personnel/personnel': RouteRecordInfo<
      '/management/personnel/personnel',
      '/management/personnel/personnel',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/management/role/': RouteRecordInfo<
      '/management/role/',
      '/management/role',
      Record<never, never>,
      Record<never, never>,
      never
    >
    '/management/role/permission': RouteRecordInfo<
      '/management/role/permission',
      '/management/role/permission',
      Record<never, never>,
      Record<never, never>,
      never
    >
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/views/404.vue': {
      routes: '/404'
      views: never
    }
    'src/views/asset/enclosure/enclosure/index.vue': {
      routes: '/asset/enclosure/enclosure/'
      views: never
    }
    'src/views/asset/enclosure/enclosure/add-enclosure.vue': {
      routes: '/asset/enclosure/enclosure/add-enclosure'
      views: never
    }
    'src/views/asset/enclosure/enclosure/detail-enclosure.vue': {
      routes: '/asset/enclosure/enclosure/detail-enclosure'
      views: never
    }
    'src/views/asset/enclosure/enclosure/edit-enclosure.vue': {
      routes: '/asset/enclosure/enclosure/edit-enclosure'
      views: never
    }
    'src/views/asset/enclosure/enclosure-floor.vue': {
      routes: '/asset/enclosure/enclosure-floor'
      views: never
    }
    'src/views/asset/enclosure/floor/index.vue': {
      routes: '/asset/enclosure/floor/'
      views: never
    }
    'src/views/asset/enclosure/floor/add-floor.vue': {
      routes: '/asset/enclosure/floor/add-floor'
      views: never
    }
    'src/views/asset/enclosure/floor/detail-floor.vue': {
      routes: '/asset/enclosure/floor/detail-floor'
      views: never
    }
    'src/views/asset/enclosure/floor/edit-floor.vue': {
      routes: '/asset/enclosure/floor/edit-floor'
      views: never
    }
    'src/views/dashboard.vue': {
      routes: '/dashboard'
      views: never
    }
    'src/views/home-view.vue': {
      routes: '/home-view'
      views: never
    }
    'src/views/login.vue': {
      routes: '/login'
      views: never
    }
    'src/views/management/personnel/add-personnel.vue': {
      routes: '/management/personnel/add-personnel'
      views: never
    }
    'src/views/management/personnel/detail-personnel.vue': {
      routes: '/management/personnel/detail-personnel'
      views: never
    }
    'src/views/management/personnel/import-personnel.vue': {
      routes: '/management/personnel/import-personnel'
      views: never
    }
    'src/views/management/personnel/import-personnel-complete.vue': {
      routes: '/management/personnel/import-personnel-complete'
      views: never
    }
    'src/views/management/personnel/import-personnel-execute.vue': {
      routes: '/management/personnel/import-personnel-execute'
      views: never
    }
    'src/views/management/personnel/personnel.vue': {
      routes: '/management/personnel/personnel'
      views: never
    }
    'src/views/management/role/index.vue': {
      routes: '/management/role/'
      views: never
    }
    'src/views/management/role/permission.vue': {
      routes: '/management/role/permission'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info> ? Info['routes'] : keyof RouteNamedMap
}
